FROM arm32v7/ubuntu:latest

RUN apt-get update && apt-get install -y locales tzdata
RUN ln -fs /usr/share/zoneinfo/Asia/Hong_Kong /etc/localtime && dpkg-reconfigure -f noninteractive tzdata

RUN rm -rf /var/lib/apt/lists/* \
    && localedef -i en_HK -c -f UTF-8 -A /usr/share/locale/locale.alias en_HK.UTF-8
ENV LANG en_HK.utf8
